### ISSUE TITLE
CBSD 10.1.2 can't edit exec_{start,stop}

### ISSUE THREAD

**Issue by yggdr** [olevole/cbsd-wwwdoc#5]
Hi,
in cbsd jconfig, trying to access/modify exec_start and exec_stop yields a
/usr/jails/cbsd/jailctl/jsetup-tui: get_construct_exec_start: not found
error. Tried on 2 amd64 machines with 10.1-RELEASE r274401
Thanks

edit
Ah shit, wrong repo... sorry :(

**Comment by olevole** [comment]
Thanks. I've forget to hide this options from menu. At the moment, I did not be able to edit these entries.  This will be fixed in 10.1.4

If you need it, and if you are familiar with the SQL syntax, it can be done directly:

~~~
% sqlite3 ~cbsd/var/db/local.sqlite
sqlite> .schema jails
~~~

You can update exec_start and exec_stop field:
~~~
sqlite> select jname,exec_start from jails;
sqlite> update jails set exec_start="/bin/sh /etc/rc" where jname="XXX";
~~~

However, this is system records. If you want to add your additional commands, use appropriate directories in ~cbsd/jails-system/$jname/{
master_poststart.d
master_poststop.d
master_prestart.d
master_prestop.d
start.d
stop.d
}

just add executable script(s) in start.d directory with a sequence of commands to be executed at jail startup.
